on: [workflow_dispatch]

name: Azure Bicep deployment
jobs:
  
  dev:
    name: Build and deploy to dev
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}        
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./infrastructure/websqlapp/main.bicep
        parameters: env=dev adminUser=${{ secrets.adminUser }} adminPassword=${{ secrets.adminPassword }}
        failOnStdErr: false
        
  staging:
    needs: dev
    name: Build and deploy to qa
    environment:
      name: qa      
    runs-on: ubuntu-latest
    steps:
    
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}        
        resourceGroupName: ${{ secrets.QA_AZURE_RG }}
        template: ./infrastructure/websqlapp/main.bicep
        parameters: env=qa adminUser=${{ secrets.qaAdminUser }} adminPassword=${{ secrets.qaAdminPassword }}
        failOnStdErr: false
